### PR TITLE
Disable all sounds policy

### LINKED ISSUE #406: Disable all sounds policy
Was requested a policy to shut up a device

### PR DESCRIPTION
**Pull request by DIOHz0r**
Signed-off-by: Domingo Oropeza <doropeza@teclib.com>

### Changes description

Added policy for disable all sounds on device

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Closes #406

### CODE REVIEW

**Comment by btry** [comment]
@ajsb85 We discussed a few days ago about the ability to "explode" this policy info more fine t umable set of policies.

The idea is to provide a way to enable or disable each type og sound individually. To disable all souds, just apply all sound policies at on the same target.. 

I don't have feedback yet about this possibility.

**Comment by ajsb85** [comment]
@rafaelje PING

**Comment by ajsb85** [comment]
@rafaelje we was waiting for you to discuss this policy before merge this PR.
References:
https://github.com/flyve-mdm/android-mdm-agent/issues/369
https://github.com/flyve-mdm/android-mdm-agent/pull/372

**Comment by rafaelje** [comment]
These are the options available at this moment to setup with audio:

# turn ringer silent options
AudioManager.RINGER_MODE_NORMAL | RINGER_MODE_SILENT | RINGER_MODE_VIBRATE

# turn on sound, enable notifications boolean
AudioManager.STREAM_SYSTEM

# notifications boolean
AudioManager.STREAM_NOTIFICATION

# alarm boolean
AudioManager.STREAM_ALARM

# ringer boolean
AudioManager.STREAM_RING

# media boolean
AudioManager.STREAM_MUSIC

**Comment by btry** [comment]
Then we need to define 6 policies, all boolean, except the first one which is a dropdown.

**Comment by rafaelje** [comment]
Correctly and maybe we can keep this policy to disable all sound at once

**Comment by btry** [comment]
> maybe we can keep this policy to disable all sound at once

Not yet. We need to develop new things for that
- priority between policies (on both backend and agent)
OR
- a new type of policy (dumb idea: some kind of meta-policy which does not applies, but instead applies several other ones ?)

I don't know yet which is the best choice. For now, let's offer granularity.

**Comment by rafaelje** [comment]
> a new type of policy (dumb idea: some kind of meta-policy which does not applies, but instead applies several other ones ?)

it's interesting to add the possibility to create a personalized policy-box with many default policies to implement at once but this is the concept of a fleet maybe add many fleets

**Comment by btry** [comment]
I think this would make things way more complicated. I would be in favor of a single policy which sets several things at one. Like a macro. The pro is that this does not requires any additional code in the  agent. The less you have logic in the agent the less it burns battery power.

**Pull request merged**
