### PR TITLE
Remove not ready policy

### PR DESCRIPTION
**Pull request by btry**
This PR removes from the project the policies which are not ready for the release 2.0

/cc @DIOHz0r @rafaelje 

For convenience, please, remove yourself any policy that you want to remove, one per commit. Doing so will allow us to revert a commit to re-add the policy after the release.

### CODE REVIEW

**Comment by DIOHz0r** [comment]
I have done the rebase and update for this PR, please review it

**Comment by ajsb85** [comment]
I don't agree, we can hide the work in progress instead of remove it.
it's a double of work.

**Comment by btry** [comment]
@ajsb85 

I had also the idea of a new column to disable policies but : 
- users may find it and try it by resetting the disable bool
- we need to add and maintain upgrade code

removing the policies in the install code is easy, and revertable with ```git revert```. This is way less work

**Comment by DIOHz0r** [comment]
Another reason is the last two commits, both policies removed can't be applied on Android systems according to @rafaelje

**Comment by btry** [comment]
when all policies to removed are in this PR we will need an extra commit to remove them when upgrading: we have some users running the development branch.

**Comment by DIOHz0r** [comment]
> when all policies to removed are in this PR we will need an extra commit to remove them when upgrading: we have some users running the development branch.

Actually this PR is ready IMO.

**Pull request merged**
