### PR TITLE
Template for installation wizard

### PR DESCRIPTION
**Pull request by btry**
Functional draft of the installation wizard

See #154

### CODE REVIEW

**Comment by btry** [comment]
some screenshots

image

image
image
image

In this screenshot, notice the first tab **Installation wizard*** vanished. We might create a feature to re-enable it.
image

**Comment by btry** [comment]
Hi @Naylin15 

I suggest we do things simple for now. We must assume some prerequisites of the plugin are met (GLPI installed, Fusion Inventory enabled, email notifications enabled).

We can re-use the installation documentation in the wiki starting from the "hard" part of  the setup, and split it into small steps each well documented in one page of the wizard.

The file tpl/config-wizard.html is a Twig template containing all the steps. This PR introduces some constants to adapt the number of steps to our needs.

**Comment by btry** [comment]
we can easily consider : 
- form inputs in some steps to be saved in the configuration of the plugin
- remove the installation prerequisite for notifications and move then in the wizard as a simple action
- add some settings (computer category, user category) not well documented and not mandatory but useful to maintain a g ood organization of objects.

The best : extend the switch from a step to an other with a non linear procedure. Example. Which is the distro of the server running Mosquitto ? (Debian 7, Debian 8, Debian 9). If the user chooses Debian 7 we can guide him to compile Mosqutto and the authentication plugin. For other choices, this is not needed.

**Comment by ajsb85** [comment]
This branch has conflicts that must be resolved

**Comment by ajsb85** [comment]
The Travis CI build failed

**Pull request merged**
