### PR TITLE
Added Flyve MDM Agent tab to computer UI

### PR DESCRIPTION
**Pull request by DIOHz0r**
## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](http://conventionalcommits.org/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Issue #218 

## What is the new behavior?
New tab added for computer UI

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by btry** [comment]
@DIOHz0r 

If I display a computer without any agent, there is a fatal error.

image

Also, lease remove the tab Flyve MDM Agent, and  keep only the display of the agent in the main tab. The itemtype Computer has too many tabs and we need to not grow this quantity.

**Comment by DIOHz0r** [comment]
ok, got it.

**Comment by btry** [comment]
Hi @DIOHz0r 

Added 2 commits on your PR. Remains to fix unit tests and we're ready to merge it.

**Comment by ajsb85** [comment]
This branch has conflicts that must be resolved

**Comment by btry** [comment]
rebased + added a test for my changes

**Pull request merged**
