### PR TITLE
Sub menu for development section

### LINKED ISSUE #558: Development section on project site
#### Observed Results:
We must normalize the development section on the project site

  
#### Expected behavior:
coverage >>>> development/coverage/
docs >>>> development/code-documentation/
development/test-reports

### LINKED ISSUE #678: Section for develop and master branch doc
#### Observed Results:
Currently we are only displaying the documentation for the develop branch, we need to add a space for the documentation on master branch

  
#### Expected behavior:
To have the documentation for changes in both develop and master branch for the project site

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Add submenu in order to have documentation for the latest-version and the develop

Normalize development folders
Remove demo mode plugin documentation since it'll be deprecated
### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |52|
|@Gianfranco97|14|
|@DIOHz0r|4|
|@hectorerb|2|

### References

Closes #678 
Closes #558  
Related #694
Depends on # N/A

### CODE REVIEW

**Comment by Naylin15** [comment]
captura de pantalla 2018-08-08 a la s 4 08 35 p m

Having a small issue with css styles to move the submenu

**Comment by Naylin15** [comment]
Changed the file structure with the new proposal as issue #678 

Still working out the css for correct display

**Comment by Gianfranco97** [comment]
localhost_4000_glpi-plugin_
localhost_4000_glpi-plugin_ 1

**Comment by Naylin15** [comment]
Added the white list for the versioning, the display is as it should, also learning how apigen generates the documentation

captura de pantalla 2018-08-13 a la s 6 24 32 p m

**Comment by Naylin15** [comment]
Fixed issue with the url generation

captura de pantalla 2018-08-14 a la s 4 43 04 p m

**Comment by Naylin15** [comment]
I'll implement a script to update the version list taking them from the folder structure, this way it'll keep things simple for the CI

**Pull request merged**
