### PR TITLE
Wizard enhancement

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description

Add new step for Fusion Inventory configuration
Rename the cron job step, it used to be REST API too
Change order of step from Email notifications > REST API > Cron job
to Email notifications > Cron job > REST API
Add new set of pages for previous requirements

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Reference #287 
#

### CODE REVIEW

**Comment by btry** [comment]
@Naylin15 It looks good so far. Just consider a new group of pages for your contribution, instead of adding new pages in the MQTT configuration group

(WIZARD_MQTT_END changed from 105 to 106 in the current diff)

**Comment by Naylin15** [comment]
All right, I'm still making some changes to fulfill the issue, I'll have that in mind

**Comment by Naylin15** [comment]
Hi, @btry 

I added a new set of pages for the first 4 steps of the wizard called requirements, but I kept the 100 - 103 count, not so sure if that's correct

But I did also add a new page for the TLS setup in the MQTT group, (still working on the information)

**Comment by btry** [comment]
It looks good, I'll run (forward and backward) it to ensure it works correctly.

**Comment by Naylin15** [comment]
Hi, @btry 

I changed the order of the requirement steps, making the first the cron job setup, and also added the TLS information

Checking the installation article I saw that we don't explain anything related to the server configuration, and I think that maybe this could be added to the wizard

**Comment by btry** [comment]
Hi @naylin

If you want to add more content, feel créé to do it. You may add it on this PR.

**Comment by Naylin15** [comment]
Hi, @btry / @DIOHz0r 

I think this PR is ready, though I'm not sure why Travis is failing

I'll do next the draft for the installation article including the wizard

**Comment by btry** [comment]
@Naylin15 The unit tests are failing for an unknown reason. I began to investigate as this blocks my PRs too.

It seems something is briken with GLPI branch master. I did not found yet the exact cause, I don't reproduce locally. For now I know that the plugin fails to install... Maybe because of Fusion Inventory which fails to install too ?

To be investigated further.

**Pull request merged**
