### PR TITLE
Update search options

### LINKED ISSUE #179: All keys of the Get Item Type Agent in the Search Option List
Hi, @btry 

Could you add the same data of the item type PluginFlyvemdmAgent in the listSearchOption endpoint?

Thanks.

### PR DESCRIPTION
**Pull request by btry**
Fix #179 

Waiting for possible other updates related to search options (#176 ?)

### CODE REVIEW

**Comment by ajsb85** [comment]
Hi, @btry 

Could you add also `PluginFlyvemdmAgent.Computer.User.firstname`?

Thank you.

**Comment by btry** [comment]
I think this is a bad idea to make available in an itemtype a data coming from an other itemtype which is not related to the first one. An agent and a user are not tightly coupled in a semantic point of view.

By the way we my need to remove the user email search option from the agent because we need to allow agents without any relatin to a (human) user in the future.

**Comment by ajsb85** [comment]
@btry Actually I can get  PluginFlyvemdmAgent.Computer.User.realname in the list of the search options

**Comment by ajsb85** [comment]
Actual search options in the Agent

```JSON
"PluginFlyvemdmAgent.name": "a.salas@ieee.org",
"PluginFlyvemdmAgent.id": 115,
"PluginFlyvemdmAgent.PluginFlyvemdmFleet.name": "not managed fleet",
"PluginFlyvemdmAgent.Computer.id": 153,
"PluginFlyvemdmAgent.Computer.serial": "LGK220AISOLZ55",
"PluginFlyvemdmAgent.Computer.User.id": 221,
"PluginFlyvemdmAgent.PluginFlyvemdmFleet.id": 7,
"PluginFlyvemdmAgent.last_contact": "2017-11-13 19:00:57",
"PluginFlyvemdmAgent.Computer.User.realname": "Salas Bastidas",
"PluginFlyvemdmAgent.version": "3.0.0",
"PluginFlyvemdmAgent.is_online": 1
```

**Comment by btry** [comment]
hummm I forgot about this. There is a background about existence of this data, and I think this should be removed mostly because the design of the plugin is going to be better shortly.

**Comment by ajsb85** [comment]
I will merge it @btry 
No continuous deployment at the moment?

**Comment by btry** [comment]
Hi

@ajsb85 I think I should remove the serial number from search options. We can get the ID of the computer, then we can get the serial number indirectly, the same way we retrieve the user name.

**Pull request merged**
