### PR TITLE
Fix styles project site

### PR DESCRIPTION
**Pull request by Vector-Blanxart**
Signed-off-by: Esteban Villegas Blanxart <evillegas@teclib.com>

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
| @Vector-Blanxart |1|

### References

Closes #N/A
Related #N/A
Depends on #N/A

### CODE REVIEW

**Comment by Vector-Blanxart** [comment]
Please @ajsb85 , @Naylin15 , review this commits.

**Comment by ajsb85** [comment]
Hi, @Vector-Blanxart 
Could you publish a screenshot of the changes?

**Comment by Vector-Blanxart** [comment]
image

**Comment by Vector-Blanxart** [comment]
image

**Comment by Naylin15** [comment]
Hi, @Vector-Blanxart 

Please remember that the *docs* type is for changes related to documentation, for these type of changes you should use the *refactor* type

**Comment by Vector-Blanxart** [comment]
image

                                         **Left-Before                                                  Right-After**

**Comment by Vector-Blanxart** [comment]
image

**Left-Before                                  Right-After**

**Pull request merged**
